/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin Backend API
 * 后台管理系统后端 API 文档，前端可通过 OpenAPI Schema 自动生成接口调用代码
 * OpenAPI spec version: 1.0.0
 */

/**
 * 登录请求参数
 */
export interface LoginDTO {
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** 验证码key（获取验证码时返回） */
  captchaKey: string;
  /** 验证码答案 */
  captchaCode: string;
}
