/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin Backend API
 * 后台管理系统后端 API 文档，前端可通过 OpenAPI Schema 自动生成接口调用代码
 * OpenAPI spec version: 1.0.0
 */
import type { SortMenuDTOItem } from './sortMenuDTOItem';

/**
 * 菜单排序请求
 */
export interface SortMenuDTO {
  /** 排序项列表 */
  items: SortMenuDTOItem[];
}
