/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin Backend API
 * 后台管理系统后端 API 文档，前端可通过 OpenAPI Schema 自动生成接口调用代码
 * OpenAPI spec version: 1.0.0
 */

/**
 * 用户信息
 */
export interface UserVO {
  /** 用户ID */
  id?: number;
  /** 用户名 */
  username?: string;
  /** 邮箱 */
  email?: string;
  /** 昵称 */
  nickname?: string;
  /** 头像 */
  avatar?: string;
  /** 状态：1-正常 0-禁用 */
  status?: number;
  /** 是否超级管理员：1-是 0-否 */
  isSuperuser?: number;
  /** 创建时间 */
  createTime?: string;
}
